/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arquitecturaglobal;

import java.awt.Color;
import javax.swing.ImageIcon;

public class Window extends javax.swing.JFrame {

    public Window() {
        initComponents();
        this.setTitle("Eventos del mouse");
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("/iconos/mouse_1.ico");
        this.setIconImage(icon.getImage());
        lapiz.setName("lapiz");
        click.setName("click");
        minijuego.setName("minijuego");
        
        lapizHover.setVisible(false);
        clickHover.setVisible(false);
        minijuegoHover.setVisible(false);
        
        panelDibujar.setVisible(false);
        panelClickear.setVisible(false);
        panelMinijuego.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        lapizHover = new javax.swing.JLabel();
        clickHover = new javax.swing.JLabel();
        minijuegoHover = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        minijuego = new javax.swing.JLabel();
        lapiz = new javax.swing.JLabel();
        click = new javax.swing.JLabel();
        panelMinijuego = new javax.swing.JPanel();
        basura = new javax.swing.JLabel();
        panelInstrucciones = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        boton = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelDibujar = new javax.swing.JPanel();
        opciones = new javax.swing.JPanel();
        borrador = new javax.swing.JLabel();
        azul = new javax.swing.JLabel();
        rojo = new javax.swing.JLabel();
        amarillo = new javax.swing.JLabel();
        panelClickear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantClicks = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(241, 250, 238));
        background.setMinimumSize(new java.awt.Dimension(660, 456));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lapizHover.setBackground(new java.awt.Color(69, 123, 157));
        lapizHover.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lapizHover.setForeground(new java.awt.Color(29, 53, 87));
        lapizHover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapizHover.setText("Dibujar en el panel");
        lapizHover.setOpaque(true);
        background.add(lapizHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 20));

        clickHover.setBackground(new java.awt.Color(69, 123, 157));
        clickHover.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clickHover.setForeground(new java.awt.Color(29, 53, 87));
        clickHover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clickHover.setText("Contador de clicks");
        clickHover.setOpaque(true);
        background.add(clickHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 20));

        minijuegoHover.setBackground(new java.awt.Color(69, 123, 157));
        minijuegoHover.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        minijuegoHover.setForeground(new java.awt.Color(29, 53, 87));
        minijuegoHover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minijuegoHover.setText("Minijuego");
        minijuegoHover.setOpaque(true);
        background.add(minijuegoHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 20));

        menu.setBackground(new java.awt.Color(230, 57, 70));
        menu.setMinimumSize(new java.awt.Dimension(70, 130));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        minijuego.setBackground(new java.awt.Color(230, 57, 70));
        minijuego.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minijuego.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/minijuegoCeleste.png"))); // NOI18N
        minijuego.setToolTipText("");
        minijuego.setOpaque(true);
        menu.add(minijuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 70, 70));

        lapiz.setBackground(new java.awt.Color(230, 57, 70));
        lapiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lapizCeleste.png"))); // NOI18N
        lapiz.setOpaque(true);
        menu.add(lapiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));
        lapiz.getAccessibleContext().setAccessibleName("lapiz");

        click.setBackground(new java.awt.Color(230, 57, 70));
        click.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        click.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clickCeleste.png"))); // NOI18N
        click.setText("  ");
        click.setToolTipText("");
        click.setOpaque(true);
        menu.add(click, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 70));
        click.getAccessibleContext().setAccessibleName("click");

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 456));

        panelMinijuego.setBackground(new java.awt.Color(255, 255, 255));
        panelMinijuego.setMinimumSize(new java.awt.Dimension(70, 130));

        basura.setForeground(new java.awt.Color(168, 218, 220));
        basura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/basura.png"))); // NOI18N

        panelInstrucciones.setBackground(new java.awt.Color(29, 53, 87));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¿Cómo jugar?");

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Si aparece un mosquito o una araña, debes aplastarlos con el click.");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Si aparece una banana o una manzana, debes arrastrarla hasta la basura.");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/banana.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/mosquito.png"))); // NOI18N

        boton.setBackground(new java.awt.Color(230, 57, 70));
        boton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        boton.setForeground(new java.awt.Color(255, 255, 255));
        boton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boton.setText("OK!");
        boton.setOpaque(true);
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/manzana.png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/arana.png"))); // NOI18N

        javax.swing.GroupLayout panelInstruccionesLayout = new javax.swing.GroupLayout(panelInstrucciones);
        panelInstrucciones.setLayout(panelInstruccionesLayout);
        panelInstruccionesLayout.setHorizontalGroup(
            panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstruccionesLayout.createSequentialGroup()
                .addGroup(panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInstruccionesLayout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9))
                            .addGroup(panelInstruccionesLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel5))))
                    .addGroup(panelInstruccionesLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInstruccionesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInstruccionesLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInstruccionesLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );
        panelInstruccionesLayout.setVerticalGroup(
            panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInstruccionesLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelInstruccionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(26, 26, 26)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelMinijuegoLayout = new javax.swing.GroupLayout(panelMinijuego);
        panelMinijuego.setLayout(panelMinijuegoLayout);
        panelMinijuegoLayout.setHorizontalGroup(
            panelMinijuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMinijuegoLayout.createSequentialGroup()
                .addGroup(panelMinijuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMinijuegoLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(basura, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMinijuegoLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(panelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelMinijuegoLayout.setVerticalGroup(
            panelMinijuegoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMinijuegoLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(panelInstrucciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(133, 133, 133)
                .addComponent(basura, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        background.add(panelMinijuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 590, 456));

        panelDibujar.setBackground(new java.awt.Color(255, 255, 255));
        panelDibujar.setMinimumSize(new java.awt.Dimension(70, 130));
        panelDibujar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        opciones.setBackground(new java.awt.Color(69, 123, 157));
        opciones.setMinimumSize(new java.awt.Dimension(70, 130));
        opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        borrador.setBackground(new java.awt.Color(255, 255, 255));
        borrador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        borrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/borrador.png"))); // NOI18N
        opciones.add(borrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 40, 30));

        azul.setBackground(new java.awt.Color(0, 0, 204));
        azul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        azul.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        azul.setOpaque(true);
        opciones.add(azul, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 20, 20));

        rojo.setBackground(new java.awt.Color(255, 0, 0));
        rojo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rojo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        rojo.setOpaque(true);
        opciones.add(rojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 20, 20));

        amarillo.setBackground(new java.awt.Color(255, 255, 51));
        amarillo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        amarillo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        amarillo.setOpaque(true);
        opciones.add(amarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 20, 20));

        panelDibujar.add(opciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 456));

        background.add(panelDibujar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 590, 456));

        panelClickear.setBackground(new java.awt.Color(255, 255, 255));
        panelClickear.setMinimumSize(new java.awt.Dimension(70, 130));
        panelClickear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 53, 87));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cantidad de clicks:");
        jLabel1.setToolTipText("");
        panelClickear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 260, 60));

        cantClicks.setBackground(new java.awt.Color(29, 53, 87));
        cantClicks.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 48)); // NOI18N
        cantClicks.setForeground(new java.awt.Color(168, 218, 220));
        cantClicks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantClicks.setText("0");
        cantClicks.setToolTipText("HOLA");
        cantClicks.setOpaque(true);
        panelClickear.add(cantClicks, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 300, 130));

        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Presione cualquier parte de la ventana para sumar clicks (el fondo blanco)");
        panelClickear.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        background.add(panelClickear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 590, 456));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseEntered
        boton.setBackground(new Color(69, 123, 157));
    }//GEN-LAST:event_botonMouseEntered

    private void botonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseClicked
        panelInstrucciones.setVisible(false);
    }//GEN-LAST:event_botonMouseClicked

    private void botonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMouseExited
        boton.setBackground(new Color(230,57,70));
    }//GEN-LAST:event_botonMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel amarillo;
    public javax.swing.JLabel azul;
    public javax.swing.JPanel background;
    public javax.swing.JLabel basura;
    public javax.swing.JLabel borrador;
    private javax.swing.JLabel boton;
    public javax.swing.JLabel cantClicks;
    public javax.swing.JLabel click;
    public javax.swing.JLabel clickHover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JLabel lapiz;
    public javax.swing.JLabel lapizHover;
    public javax.swing.JPanel menu;
    public javax.swing.JLabel minijuego;
    public javax.swing.JLabel minijuegoHover;
    public javax.swing.JPanel opciones;
    public javax.swing.JPanel panelClickear;
    public javax.swing.JPanel panelDibujar;
    public javax.swing.JPanel panelInstrucciones;
    public javax.swing.JPanel panelMinijuego;
    public javax.swing.JLabel rojo;
    // End of variables declaration//GEN-END:variables
}
