/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package arquitecturaglobal;

import javax.swing.ImageIcon;

public class Window extends javax.swing.JFrame {

    public Window() {
        initComponents();
        this.setTitle("Eventos del mouse");
        this.setLocationRelativeTo(null);
        ImageIcon icon = new ImageIcon("/iconos/mouse_1.ico");
        this.setIconImage(icon.getImage());
        lapiz.setName("lapiz");
        click.setName("click");
        
        lapizHover.setVisible(false);
        clickHover.setVisible(false);
        
        panelDibujar.setVisible(false);
        panelClickear.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JPanel();
        lapizHover = new javax.swing.JLabel();
        clickHover = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        lapiz = new javax.swing.JLabel();
        click = new javax.swing.JLabel();
        panelClickear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cantClicks = new javax.swing.JLabel();
        panelDibujar = new javax.swing.JPanel();
        opciones = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        background.setBackground(new java.awt.Color(241, 250, 238));
        background.setMinimumSize(new java.awt.Dimension(660, 456));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lapizHover.setBackground(new java.awt.Color(69, 123, 157));
        lapizHover.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lapizHover.setForeground(new java.awt.Color(29, 53, 87));
        lapizHover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapizHover.setText("Dibujar en el panel");
        lapizHover.setOpaque(true);
        background.add(lapizHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 120, 20));

        clickHover.setBackground(new java.awt.Color(69, 123, 157));
        clickHover.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        clickHover.setForeground(new java.awt.Color(29, 53, 87));
        clickHover.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        clickHover.setText("Contador de clicks");
        clickHover.setOpaque(true);
        background.add(clickHover, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 120, 20));

        menu.setBackground(new java.awt.Color(230, 57, 70));
        menu.setMinimumSize(new java.awt.Dimension(70, 130));
        menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lapiz.setBackground(new java.awt.Color(230, 57, 70));
        lapiz.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lapiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/lapizCeleste.png"))); // NOI18N
        lapiz.setOpaque(true);
        menu.add(lapiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 70));
        lapiz.getAccessibleContext().setAccessibleName("lapiz");

        click.setBackground(new java.awt.Color(230, 57, 70));
        click.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        click.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/clickCeleste.png"))); // NOI18N
        click.setText(" ");
        click.setToolTipText("");
        click.setOpaque(true);
        menu.add(click, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 70, 70));
        click.getAccessibleContext().setAccessibleName("click");

        background.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 456));

        panelClickear.setBackground(new java.awt.Color(255, 255, 255));
        panelClickear.setMinimumSize(new java.awt.Dimension(70, 130));
        panelClickear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(29, 53, 87));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cantidad de clicks:");
        jLabel1.setToolTipText("");
        panelClickear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 260, 60));

        cantClicks.setBackground(new java.awt.Color(29, 53, 87));
        cantClicks.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 1, 48)); // NOI18N
        cantClicks.setForeground(new java.awt.Color(168, 218, 220));
        cantClicks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cantClicks.setText("0");
        cantClicks.setToolTipText("HOLA");
        cantClicks.setOpaque(true);
        panelClickear.add(cantClicks, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 300, 130));

        background.add(panelClickear, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 590, 456));

        panelDibujar.setBackground(new java.awt.Color(255, 255, 255));
        panelDibujar.setMinimumSize(new java.awt.Dimension(70, 130));

        opciones.setBackground(new java.awt.Color(69, 123, 157));
        opciones.setMinimumSize(new java.awt.Dimension(70, 130));
        opciones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelDibujarLayout = new javax.swing.GroupLayout(panelDibujar);
        panelDibujar.setLayout(panelDibujarLayout);
        panelDibujarLayout.setHorizontalGroup(
            panelDibujarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDibujarLayout.createSequentialGroup()
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 560, Short.MAX_VALUE))
        );
        panelDibujarLayout.setVerticalGroup(
            panelDibujarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDibujarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(opciones, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        background.add(panelDibujar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 590, 456));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel background;
    public javax.swing.JLabel cantClicks;
    public javax.swing.JLabel click;
    public javax.swing.JLabel clickHover;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel lapiz;
    public javax.swing.JLabel lapizHover;
    public javax.swing.JPanel menu;
    public javax.swing.JPanel opciones;
    public javax.swing.JPanel panelClickear;
    public javax.swing.JPanel panelDibujar;
    // End of variables declaration//GEN-END:variables
}
